name: Publish Maven Package

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

  test:
    runs-on: ubuntu-latest
    depends-on: setup

    steps:
      - name: Run Tests with Maven
        run: mvn --batch-mode --update-snapshots clean test -s $GITHUB_WORKSPACE/settings.xml

  package:
    runs-on: ubuntu-latest
    depends-on: test

    steps:
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
