name: Publish Maven Package

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Maven Settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "github", "username": "penguineer", "password": "${GITHUB_TOKEN_REF}"}]'
          githubServer: false

      - name: Run Tests with Maven
        run: mvn --batch-mode --update-snapshots clean test
        env:
          GITHUB_TOKEN_REF: ${{ secrets.GH_MAVEN_TOKEN }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          GITHUB_TOKEN_REF: ${{ secrets.GH_MAVEN_TOKEN }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN_REF: ${{ secrets.GH_MAVEN_TOKEN }}
